### ISSUE TITLE
[Umbrella] Upcoming changes

### ISSUE THREAD

**Issue by cometkim** [daangn/seed-design#39]
BREAKING CHANGES
------

all:
- [ ] Will be rebranded to "Seed Design"
- [ ] Move packages to `@seed-design/*`
- [ ] Change all integration methods in the form of using global css variables.

design-token:
- [ ] Replace the design token source from TypeScript to a platform-agnostic format ([DTCG format](https://design-tokens.github.io/community-group/format/) or [custom DSL](https://github.com/daangn/karrot-ui/discussions/36))
  - [ ] (WIP) KDT Spec: https://github.com/daangn/karrot-ui/pull/41
- [ ] Generated token codes will be grouped as `scale` or `semantic`
  - e.g. `colors.background` -> `semantic.color.background`, `color-carrot-400` -> `scale-color-carrot-400`
  - This reduces the impedance mismatch between the mental model and the code and makes searching and static analysis easier.
- [ ] Move CSS resources to the separated package. e.g. `@seed-design/css`

Features Improvements
-----------

all:
- [ ] Fix browserslist target to support iOS 13.0

design-token:

- [ ] Newly defined semantic tokens
- [ ] Add static tokens
- [ ] Add support for Typography tokens

New Libs
-----------

- [ ] Add some opinionated reference integration for [Stitches](https://stitches.dev/) or [vanilla-extract](https://vanilla-extract.style/)
- [ ] Gatsby plugin
